[package]
name = "seducee"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
tokio = { version = "1.49.0", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
